namespace HealthDemo.Models.SIO
{
    public class BaseModel
    {
        //// Lista degli Oggetti presenti nel modello  
        //public List<System.Type> DataObjects { get; } = new List<Type>() 
        //{
        //     typeof(HealthDemo.Models.SIO.Act.Prestazione)
        //    ,typeof(HealthDemo.Models.SIO.Act.Attivita)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelPrestazioneCampione)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelPrestazioneUsa)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelOrganizzazioneContiene)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelAttivitaTipoCampione)
        //    ,typeof(HealthDemo.Models.SIO.Patient.Comune)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.CategoriaDatoClinico)
        //    ,typeof(HealthDemo.Models.SIO.Act.TipoEpisodio)
        //    ,typeof(HealthDemo.Models.SIO.Common.Richiesta)
        //    ,typeof(HealthDemo.Models.SIO.Patient.Episodio)
        //    ,typeof(HealthDemo.Models.SIO.Patient.Nazione)
        //    ,typeof(HealthDemo.Models.SIO.Patient.Distretto)
        //    ,typeof(HealthDemo.Models.SIO.Resource.Farmaco)
        //    ,typeof(HealthDemo.Models.SIO.Resource.Attrezzatura)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.RisultatoEsame)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.TipoDatoClinico)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.StatoSalute)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.RelPrestazioneDatoClinico)
        //    ,typeof(HealthDemo.Models.SIO.Resource.Sala)
        //    ,typeof(HealthDemo.Models.SIO.Resource.Materiale)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelAttivitaRichiestaDa)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelAttivitaUsa)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.DocumentoClinico)
        //    ,typeof(HealthDemo.Models.SIO.Patient.Paziente)
        //    ,typeof(HealthDemo.Models.SIO.Act.Campione)
        //    ,typeof(HealthDemo.Models.SIO.Common.Organizzazione)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelAttivitaErogataDa)
        //    ,typeof(HealthDemo.Models.SIO.Resource.Personale)
        //    ,typeof(HealthDemo.Models.SIO.Act.TipoAttivita)
        //    ,typeof(HealthDemo.Models.SIO.Common.TipoRichiesta)
        //    ,typeof(HealthDemo.Models.SIO.Act.TipoOrganizzazione)
        //    ,typeof(HealthDemo.Models.SIO.Resource.TipoRisorsa)
        //    ,typeof(HealthDemo.Models.SIO.Act.TipoCampione)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.ParametroVitale)
        //    ,typeof(HealthDemo.Models.SIO.Act.RelAttivitaContiene)
        //    ,typeof(HealthDemo.Models.SIO.Costs.Diagnosi)
        //    ,typeof(HealthDemo.Models.SIO.Costs.TipoDiagnosi)
        //};
        //// Lista degli Oggetti di selezione presenti nel modello  
        //public List<System.Type> SelectionFilterObjects { get; } = new List<Type>()
        //{
        //     typeof(HealthDemo.Models.SIO.Act.SelPrestazione)
        //    ,typeof(HealthDemo.Models.SIO.Act.SelAttivita)
        //    ,typeof(HealthDemo.Models.SIO.Patient.SelComune)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.SelCategoriaDatoClinico)
        //    ,typeof(HealthDemo.Models.SIO.Act.SelTipoEpisodio)
        //    ,typeof(HealthDemo.Models.SIO.Common.SelRichiesta)
        //    ,typeof(HealthDemo.Models.SIO.Patient.SelEpisodio)
        //    ,typeof(HealthDemo.Models.SIO.Patient.SelNazione)
        //    ,typeof(HealthDemo.Models.SIO.Patient.SelDistretto)
        //    ,typeof(HealthDemo.Models.SIO.Resource.SelFarmaco)
        //    ,typeof(HealthDemo.Models.SIO.Resource.SelAttrezzatura)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.SelRisultatoEsame)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.SelTipoDatoClinico)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.SelStatoSalute)
        //    ,typeof(HealthDemo.Models.SIO.Resource.SelSala)
        //    ,typeof(HealthDemo.Models.SIO.Resource.SelMateriale)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.SelDocumentoClinico)
        //    ,typeof(HealthDemo.Models.SIO.Patient.SelPaziente)
        //    ,typeof(HealthDemo.Models.SIO.Act.SelCampione)
        //    ,typeof(HealthDemo.Models.SIO.Common.SelOrganizzazione)
        //    ,typeof(HealthDemo.Models.SIO.Resource.SelPersonale)
        //    ,typeof(HealthDemo.Models.SIO.Act.SelTipoAttivita)
        //    ,typeof(HealthDemo.Models.SIO.Common.SelTipoRichiesta)
        //    ,typeof(HealthDemo.Models.SIO.Act.SelTipoOrganizzazione)
        //    ,typeof(HealthDemo.Models.SIO.Resource.SelTipoRisorsa)
        //    ,typeof(HealthDemo.Models.SIO.Act.SelTipoCampione)
        //    ,typeof(HealthDemo.Models.SIO.HealthData.SelParametroVitale)
        //    ,typeof(HealthDemo.Models.SIO.Costs.SelDiagnosi)
        //    ,typeof(HealthDemo.Models.SIO.Costs.SelTipoDiagnosi)
        //};
    }
}

